### ISSUE TITLE
Define Item categories and add them to a backend database

### ISSUE THREAD

**Issue by TrizML** [devhausleipzigacademy/camp5-final-project#27]
define the categories for the items on the platform

from the PO:

Kitchen
- Appliances (Blender, Mixer, tortilla press,toaster)
- Pots/pans/forms
- Cutlery (Besteck)
- Dishes (plates/bowls)

requirements for filtering items ( swap / free / only in specific distance?)
- Appliances
  - Type 
    - Toaster (Two or four spaces for bread)
    - Blender (Power level, size of container)
  - Age
  - Condition (zustand)
  - Brand
  - Electronic/Manual
  - Color
- Pots/Pans/forms
  - Type 
  - Age
  - Condition (zustand)
  - Brand
  - Color
  - Dimensions
  - Material
- Cutlery
  - Type
  - Dimensions
  - Material
  - Condition
- Dishes
  - Type
  - Condition (zustand)
  - Color(s)
  - Material
  - Dimensions

**Comment by nort4n** [comment]
encountered problems with complex nested data structure. waiting for input from @franzwollang
