### ISSUE TITLE
Set Libraries:

### ISSUE THREAD

**Issue by TrizML** [devhausleipzigacademy/camp5-final-project#4]
- [x] tailwind
- [x] uuid
- [x] dotenv
- [x] TypeBox/ZOD
- [x] Nodemailer
- [x] date-fns
- [x] leaflet
- [x] Open Street Maps
- [x] Zustand
- [x] Mapbox
- [x] Openlayers
- [x] Axios

**Comment by inpatr** [comment]
+ Open Street Maps - nothing to install, we use URL
+ installed ZOD, not gonna use Typebox now
+ tailwind is set up and tested
