### ISSUE TITLE
Login mechanism

### ISSUE THREAD

**Issue by TrizML** [devhausleipzigacademy/camp5-final-project#88]

**Comment by deankemball** [comment]
can now log in with google authentication. click the google icon to try it out. 
facebook and email / password auth yet to come.

**Comment by inpatr** [comment]
email / password auth works, correct? @deankemball

**Comment by deankemball** [comment]
yes but you as it was in the final stage of the project only one username and password works as defined in the auth page. there is no user creation process

**Comment by inpatr** [comment]
next steps are #81
