### ISSUE TITLE
On the users list add functionality to delete, edit items

### ISSUE THREAD

**Issue by TrizML** [devhausleipzigacademy/camp5-final-project#93]
Add gestures to show buttons that allow updating or deleting of items

**Comment by inpatr** [comment]
hover over item div: show icons for delete & edit on the right

**Comment by JonathanWagne** [comment]
> hover over item div: show icons for delete & edit on the right

Change: on mobile not able to hover. Added Heroicons instead

**Comment by JonathanWagne** [comment]
Include Endpoint to delete Items

**Comment by nort4n** [comment]
deleting items from the user item list by clicking on the delete item works, but list is not re-rendered

**Comment by inpatr** [comment]
List rerenders but you have to click "YES" 2 times

**Comment by inpatr** [comment]
STILL NEED:
- [ ] post edited Item to DB and redirect to useritemlist

**Comment by inpatr** [comment]
create new issue for easier overview
